### ISSUE TITLE
Some packages may need xvfb

### ISSUE THREAD

**Issue by timholy** [JuliaCI/Nanosoldier.jl#167]
GtkObservables and ImageView both need `xvfb` since they require a display: https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/d1c3641_vs_7242f78/report.html (from https://github.com/JuliaLang/PrecompileTools.jl/pull/13). Either that, or they could just be excluded from PkgEval runs.

**Comment by maleadt** [comment]
PkgEval already supports xvfb, and launches it by default, so I'm not sure why that isn't working here. In fact, PkgEval's test suite even verifies that Gtk.jl passes tests.

**Comment by maleadt** [comment]
As mentioned above, PkgEval already provides xvfb. The fact that you're running into an xvfb launch failure probably indicates that launching the sandbox doesn't work, since xvfb is the first one started. That's probably because of a permission error, as GitHub uses Ubuntu 24.04 which disables user namespaces by default.

Have a look at the PkgEval `.github/workflows/ci.yml` to see how we re-enable this capability, allowing PkgEval to run.
