### ISSUE TITLE
Improvements to PkgEval output

### ISSUE THREAD

**Issue by maleadt** [JuliaCI/Nanosoldier.jl#173]
Now that the changes to the PkgEval logs are live, thanks to @LilithHafner, there's a couple improvements we may want to consider. See for example the log at https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_date/2023-08/06/report.html:

- the characters used to denote success/crash don't seem equally wide, leading to differences in cell width:

  <img width="1015" alt="image" src="https://github.com/JuliaCI/Nanosoldier.jl/assets/383068/20093d38-2a73-47f1-9806-67c618e2dd83">

- I wonder if we could use different characters to encode success/fail/crash, so that it becomes obvious when a simple failure becomes a crash. Maybe using the emoji's that are already used in the headers: ✖ for failure, ❗ for crash
- something seems wrong here: 

  <img width="1165" alt="image" src="https://github.com/JuliaCI/Nanosoldier.jl/assets/383068/eaeeb6b3-035e-4673-8bc5-5b06c1adf0da">

**Comment by LilithHafner** [comment]
- I think that is font dependent, on opera, chrome, and firefox on macos I get
<img width="1006" alt="Screenshot 2023-08-08 at 11 19 31 AM" src="https://github.com/JuliaCI/Nanosoldier.jl/assets/60898866/113bbe18-8c8f-4c0f-8da1-435d7d12e007">

- Sure, or at least we could have a key. Color-coding would be even better :)
- Yep. #174
- Github rendering of the markdown file hosted at https://github.com/JuliaCI/NanosoldierReports/blob/master/pkgeval/by_date/2023-08/06/report.md also started failing, I suspect due to increased file size and https://github.com/github/markup/issues/1449
